name: SSH Key Discovery

on:
  push:
    branches: [main]

jobs: 
  grade:
    runs-on: ubuntu-latest
    steps:
      - name: Discover context 
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}   
        run: echo "$GITHUB_CONTEXT"
        shell: bash